apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: shipit-access
subjects:
  - kind: ServiceAccount
    name: default
    namespace: shipit
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
